name: apc2022
description: apc2022 group assignment

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^0.13.5
  swipe_cards: ^1.0.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.7
  video_player: ^2.4.10
  google_fonts: ^3.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Murecho
      fonts:
        - asset: assets/fonts/Murecho/static/Murecho-Thin.ttf
          weight: 100
        - asset: assets/fonts/Murecho/static/Murecho-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Murecho/static/Murecho-Light.ttf
          weight: 300
        - asset: assets/fonts/Murecho/static/Murecho-Regular.ttf
          weight: 400
        - asset: assets/fonts/Murecho/static/Murecho-Medium.ttf
          weight: 500
        - asset: assets/fonts/Murecho/static/Murecho-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Murecho/static/Murecho-Bold.ttf
          weight: 700
        - asset: assets/fonts/Murecho/static/Murecho-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Murecho/static/Murecho-Black.ttf
          weight: 900
